<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
# Setup the reports folders and prefix filename with date-timestamp
<%
unless Dir.exist?("reports")
	Dir.mkdir('reports')
end

Dir.chdir("reports")

puts "\n>>> TEST REPORT will be filed in the following path:\n" + Dir.pwd + "\/\n\n"

reportfile = "reports\/" + Time.now.strftime('%Y-%m-%d_%H-%M-%S') + "-test-report.html"

Dir.chdir("..")
%>

<% common = "--tags ~@wip --tags ~@ignore --strict" %>

default: --profile staging --profile html_report <%= common%> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip

html_report: --format pretty --format html --out <%= reportfile%> --format junit --out reports
staging: TARGET=staging
live: TARGET=live