<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>

<%
Dir.chdir("reports")
unless Dir.exist?(Time.now.strftime('%Y-%m-%d'))
	Dir.mkdir(Time.now.strftime('%Y-%m-%d'))
end

puts "\n>>> TEST REPORT will be filed in the following path:\n" + Dir.pwd + "\/" + Time.now.strftime('%Y-%m-%d')+ "\n\n"

reportfile = "reports\/" + Time.now.strftime('%Y-%m-%d') + "\/" + Time.now.strftime('%Y-%m-%d_%H-%M-%S') + "-test-report.html"

Dir.chdir("..")
%>

<% common = "--tags ~@wip --tags ~@ignore --strict" %>

default: --profile html_report <%= common%> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip

html_report: --format pretty --format html --out <%= reportfile%>